[package]
name = "seshat"
version = "0.3.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache-2.0"
description = "A matrix message logger with full text search support"

[dependencies]
tantivy = { git = "https://github.com/matrix-org/tantivy", branch = "reader_readonly_source" }
tinysegmenter = "0.1"
rusqlite = { version = "0.20", features = ["sqlcipher"] }
fs_extra = "1.1.0"
r2d2_sqlite = "0.12"
r2d2 = "0.8"
failure = "0.1.5"
aes-ctr = "0.3.0"
crypto-mac = "0.7.0"
hmac = "0.7.1"
sha2 = "0.8.1"
hkdf = "0.8.0"
pbkdf2 = "0.3.0"
rand = "0.7.2"
zeroize = "1.0.0"
byteorder = "1.3.2"

[dev-dependencies]
tempfile = "3.1"
lazy_static = "1.3"
fake = "*"
